/* testdata.c generated by valac 0.18.0, the Vala compiler
 * generated from testdata.vala, do not modify */

/* testcollection.vala
 *
 * Copyright (C) 2012  Maciej Piechotka
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 *      Maciej Piechotka <uzytkownik2@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_TEST_DATA (test_data_get_type ())
#define TEST_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEST_DATA, TestData))
#define TEST_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEST_DATA, TestDataClass))
#define IS_TEST_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEST_DATA))
#define IS_TEST_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEST_DATA))
#define TEST_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEST_DATA, TestDataClass))

typedef struct _TestData TestData;
typedef struct _TestDataClass TestDataClass;
typedef struct _TestDataPrivate TestDataPrivate;
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecTestData ParamSpecTestData;

struct _TestData {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TestDataPrivate * priv;
};

struct _TestDataClass {
	GTypeClass parent_class;
	void (*finalize) (TestData *self);
};

struct _ParamSpecTestData {
	GParamSpec parent_instance;
};


static gpointer test_data_parent_class = NULL;
static gchar** test_data_ones;
static gint test_data_ones_length1;
static gchar** test_data_ones = NULL;
static gint test_data_ones_length1 = 0;
static gint _test_data_ones_size_ = 0;
static gchar** test_data_tens;
static gint test_data_tens_length1;
static gchar** test_data_tens = NULL;
static gint test_data_tens_length1 = 0;
static gint _test_data_tens_size_ = 0;
static gchar* test_data_hundred;
static gchar* test_data_hundred = NULL;
static gchar** test_data_thousands;
static gint test_data_thousands_length1;
static gchar** test_data_thousands = NULL;
static gint test_data_thousands_length1 = 0;
static gint _test_data_thousands_size_ = 0;
static guint test_data_DATA_SIZE;
static guint test_data_DATA_SIZE = 0U;
static gchar** test_data_data;
static gint test_data_data_length1;
static gchar** test_data_data = NULL;
static gint test_data_data_length1 = 0;
static gint _test_data_data_size_ = 0;
static gchar** test_data_sorted_data;
static gint test_data_sorted_data_length1;
static gchar** test_data_sorted_data = NULL;
static gint test_data_sorted_data_length1 = 0;
static gint _test_data_sorted_data_size_ = 0;
static guint* test_data_random_idx;
static gint test_data_random_idx_length1;
static guint* test_data_random_idx = NULL;
static gint test_data_random_idx_length1 = 0;
static gint _test_data_random_idx_size_ = 0;

gpointer test_data_ref (gpointer instance);
void test_data_unref (gpointer instance);
GParamSpec* param_spec_test_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_test_data (GValue* value, gpointer v_object);
void value_take_test_data (GValue* value, gpointer v_object);
gpointer value_get_test_data (const GValue* value);
GType test_data_get_type (void) G_GNUC_CONST;
enum  {
	TEST_DATA_DUMMY_PROPERTY
};
static guint test_data_data_size (void);
static gchar** test_data_create_data (guint count, int* result_length1);
static gchar** test_data_sort_array (gchar** array, int array_length1, int* result_length1);
static gchar** _vala_array_dup1 (gchar** self, int length);
static guint* test_data_draw_numbers (guint n, guint k, int* result_length1);
#define TEST_DATA_RND_IDX_SIZE ((guint) 8)
gchar** test_data_get_data (int* result_length1);
gchar** test_data_get_sorted_data (int* result_length1);
guint* test_data_get_drawn_numbers (int* result_length1);
static gchar* test_data_print3digit (guint n);
static gint __lambda2_ (const gchar* a, const gchar* b);
static gint ___lambda2__gcompare_data_func (gconstpointer a, gconstpointer b, gpointer self);
TestData* test_data_new (void);
TestData* test_data_construct (GType object_type);
static void test_data_finalize (TestData* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static guint test_data_data_size (void) {
	guint result = 0U;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	gint _tmp2_;
	_tmp1_ = g_test_quick ();
	if (_tmp1_) {
		_tmp0_ = 128;
	} else {
		_tmp0_ = 1024;
	}
	_tmp2_ = _tmp0_;
	result = (guint) _tmp2_;
	return result;
}


gchar** test_data_get_data (int* result_length1) {
	gchar** result = NULL;
	GTypeClass* _tmp0_ = NULL;
	GTypeClass* klass;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = g_type_class_ref (TYPE_TEST_DATA);
	klass = _tmp0_;
	G_TYPE_FROM_CLASS (klass);
	_tmp1_ = test_data_data;
	_tmp1__length1 = test_data_data_length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	_g_type_class_unref0 (klass);
	return result;
}


gchar** test_data_get_sorted_data (int* result_length1) {
	gchar** result = NULL;
	GTypeClass* _tmp0_ = NULL;
	GTypeClass* klass;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = g_type_class_ref (TYPE_TEST_DATA);
	klass = _tmp0_;
	G_TYPE_FROM_CLASS (klass);
	_tmp1_ = test_data_sorted_data;
	_tmp1__length1 = test_data_sorted_data_length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	_g_type_class_unref0 (klass);
	return result;
}


guint* test_data_get_drawn_numbers (int* result_length1) {
	guint* result = NULL;
	GTypeClass* _tmp0_ = NULL;
	GTypeClass* klass;
	guint* _tmp1_;
	gint _tmp1__length1;
	guint* _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = g_type_class_ref (TYPE_TEST_DATA);
	klass = _tmp0_;
	G_TYPE_FROM_CLASS (klass);
	_tmp1_ = test_data_random_idx;
	_tmp1__length1 = test_data_random_idx_length1;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	_g_type_class_unref0 (klass);
	return result;
}


static guint* test_data_draw_numbers (guint n, guint k, int* result_length1) {
	guint* result = NULL;
	guint _tmp0_;
	guint* _tmp1_ = NULL;
	guint* _result_;
	gint _result__length1;
	gint __result__size_;
	guint _tmp31_;
	gint _tmp32_ = 0;
	guint* _tmp33_;
	gint _tmp33__length1;
	guint* _tmp34_;
	gint _tmp34__length1;
	_tmp0_ = n;
	_tmp1_ = g_new0 (guint, _tmp0_);
	_result_ = _tmp1_;
	_result__length1 = _tmp0_;
	__result__size_ = _result__length1;
	{
		guint i;
		i = (guint) 0;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_;
				guint _tmp5_;
				guint _tmp6_;
				guint* _tmp7_;
				gint _tmp7__length1;
				guint _tmp8_;
				guint _tmp9_;
				guint _tmp10_;
				_tmp3_ = _tmp2_;
				if (!_tmp3_) {
					guint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = n;
				if (!(_tmp5_ < _tmp6_)) {
					break;
				}
				_tmp7_ = _result_;
				_tmp7__length1 = _result__length1;
				_tmp8_ = i;
				_tmp9_ = i;
				_tmp7_[_tmp8_] = _tmp9_;
				_tmp10_ = _tmp7_[_tmp8_];
			}
		}
	}
	{
		guint _tmp11_;
		guint i;
		_tmp11_ = n;
		i = _tmp11_ - 1;
		{
			gboolean _tmp12_;
			_tmp12_ = TRUE;
			while (TRUE) {
				gboolean _tmp13_;
				guint _tmp15_;
				guint _tmp16_;
				gint32 _tmp17_ = 0;
				gint j;
				guint* _tmp18_;
				gint _tmp18__length1;
				guint _tmp19_;
				guint _tmp20_;
				guint tmp;
				guint* _tmp21_;
				gint _tmp21__length1;
				guint _tmp22_;
				guint* _tmp23_;
				gint _tmp23__length1;
				gint _tmp24_;
				guint _tmp25_;
				guint _tmp26_;
				guint* _tmp27_;
				gint _tmp27__length1;
				gint _tmp28_;
				guint _tmp29_;
				guint _tmp30_;
				_tmp13_ = _tmp12_;
				if (!_tmp13_) {
					guint _tmp14_;
					_tmp14_ = i;
					i = _tmp14_ - 1;
				}
				_tmp12_ = FALSE;
				_tmp15_ = i;
				if (!(_tmp15_ >= ((guint) 1))) {
					break;
				}
				_tmp16_ = i;
				_tmp17_ = g_test_rand_int_range ((gint32) 0, (gint32) (_tmp16_ + 1));
				j = (gint) _tmp17_;
				_tmp18_ = _result_;
				_tmp18__length1 = _result__length1;
				_tmp19_ = i;
				_tmp20_ = _tmp18_[_tmp19_];
				tmp = _tmp20_;
				_tmp21_ = _result_;
				_tmp21__length1 = _result__length1;
				_tmp22_ = i;
				_tmp23_ = _result_;
				_tmp23__length1 = _result__length1;
				_tmp24_ = j;
				_tmp25_ = _tmp23_[_tmp24_];
				_tmp21_[_tmp22_] = _tmp25_;
				_tmp26_ = _tmp21_[_tmp22_];
				_tmp27_ = _result_;
				_tmp27__length1 = _result__length1;
				_tmp28_ = j;
				_tmp29_ = tmp;
				_tmp27_[_tmp28_] = _tmp29_;
				_tmp30_ = _tmp27_[_tmp28_];
			}
		}
	}
	_tmp31_ = k;
	_tmp32_ = (gint) _tmp31_;
	_result_ = g_renew (guint, _result_, (gint) _tmp31_);
	(_tmp32_ > _result__length1) ? memset (_result_ + _result__length1, 0, sizeof (guint) * (_tmp32_ - _result__length1)) : NULL;
	_result__length1 = _tmp32_;
	__result__size_ = _tmp32_;
	_tmp33_ = _result_;
	_tmp33__length1 = _result__length1;
	_result_ = NULL;
	_tmp34_ = _tmp33_;
	_tmp34__length1 = _tmp33__length1;
	if (result_length1) {
		*result_length1 = _tmp34__length1;
	}
	result = _tmp34_;
	_result_ = (g_free (_result_), NULL);
	return result;
}


static gchar* test_data_print3digit (guint n) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	guint _tmp1_;
	const gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* h;
	guint _tmp14_;
	gchar** _tmp15_;
	gint _tmp15__length1;
	guint _tmp16_;
	const gchar* _tmp17_;
	const gchar* t;
	guint _tmp18_ = 0U;
	guint _tmp19_;
	gchar** _tmp20_;
	gint _tmp20__length1;
	guint _tmp23_;
	gchar** _tmp24_;
	gint _tmp24__length1;
	guint _tmp25_;
	const gchar* _tmp26_;
	const gchar* o;
	const gchar* _tmp27_ = NULL;
	const gchar* _tmp28_;
	const gchar* _tmp30_ = NULL;
	gboolean _tmp31_ = FALSE;
	const gchar* _tmp32_;
	gboolean _tmp37_;
	const gchar* _tmp38_ = NULL;
	const gchar* _tmp39_;
	const gchar* _tmp41_ = NULL;
	gboolean _tmp42_ = FALSE;
	const gchar* _tmp43_;
	gboolean _tmp45_;
	const gchar* _tmp46_ = NULL;
	const gchar* _tmp47_;
	const gchar* _tmp49_;
	const gchar* _tmp50_;
	const gchar* _tmp51_;
	const gchar* _tmp52_;
	const gchar* _tmp53_;
	gchar* _tmp54_ = NULL;
	_tmp1_ = n;
	if (_tmp1_ >= ((guint) 200)) {
		gchar** _tmp2_;
		gint _tmp2__length1;
		guint _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_ = NULL;
		_tmp2_ = test_data_ones;
		_tmp2__length1 = test_data_ones_length1;
		_tmp3_ = n;
		_tmp4_ = _tmp2_[_tmp3_ / 100];
		_tmp5_ = test_data_hundred;
		_tmp6_ = g_strdup_printf ("%s %s", _tmp4_, _tmp5_);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp6_;
	} else {
		const gchar* _tmp7_ = NULL;
		guint _tmp8_;
		const gchar* _tmp10_;
		gchar* _tmp11_;
		_tmp8_ = n;
		if (_tmp8_ >= ((guint) 100)) {
			const gchar* _tmp9_;
			_tmp9_ = test_data_hundred;
			_tmp7_ = _tmp9_;
		} else {
			_tmp7_ = NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp11_ = g_strdup (_tmp10_);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp11_;
	}
	_tmp12_ = _tmp0_;
	_tmp13_ = g_strdup (_tmp12_);
	h = _tmp13_;
	_tmp14_ = n;
	n = _tmp14_ % 100;
	_tmp15_ = test_data_tens;
	_tmp15__length1 = test_data_tens_length1;
	_tmp16_ = n;
	_tmp17_ = _tmp15_[_tmp16_ / 10];
	t = _tmp17_;
	_tmp19_ = n;
	_tmp20_ = test_data_ones;
	_tmp20__length1 = test_data_ones_length1;
	if (_tmp19_ >= ((guint) _tmp20__length1)) {
		guint _tmp21_;
		_tmp21_ = n;
		_tmp18_ = _tmp21_ % 10;
	} else {
		guint _tmp22_;
		_tmp22_ = n;
		_tmp18_ = _tmp22_;
	}
	_tmp23_ = _tmp18_;
	n = _tmp23_;
	_tmp24_ = test_data_ones;
	_tmp24__length1 = test_data_ones_length1;
	_tmp25_ = n;
	_tmp26_ = _tmp24_[_tmp25_];
	o = _tmp26_;
	_tmp28_ = h;
	if (_tmp28_ != NULL) {
		const gchar* _tmp29_;
		_tmp29_ = h;
		_tmp27_ = _tmp29_;
	} else {
		_tmp27_ = "";
	}
	_tmp32_ = h;
	if (_tmp32_ != NULL) {
		gboolean _tmp33_ = FALSE;
		const gchar* _tmp34_;
		gboolean _tmp36_;
		_tmp34_ = t;
		if (_tmp34_ != NULL) {
			_tmp33_ = TRUE;
		} else {
			const gchar* _tmp35_;
			_tmp35_ = o;
			_tmp33_ = _tmp35_ != NULL;
		}
		_tmp36_ = _tmp33_;
		_tmp31_ = _tmp36_;
	} else {
		_tmp31_ = FALSE;
	}
	_tmp37_ = _tmp31_;
	if (_tmp37_) {
		_tmp30_ = " ";
	} else {
		_tmp30_ = "";
	}
	_tmp39_ = t;
	if (_tmp39_ != NULL) {
		const gchar* _tmp40_;
		_tmp40_ = t;
		_tmp38_ = _tmp40_;
	} else {
		_tmp38_ = "";
	}
	_tmp43_ = t;
	if (_tmp43_ != NULL) {
		const gchar* _tmp44_;
		_tmp44_ = o;
		_tmp42_ = _tmp44_ != NULL;
	} else {
		_tmp42_ = FALSE;
	}
	_tmp45_ = _tmp42_;
	if (_tmp45_) {
		_tmp41_ = "-";
	} else {
		_tmp41_ = "";
	}
	_tmp47_ = o;
	if (_tmp47_ != NULL) {
		const gchar* _tmp48_;
		_tmp48_ = o;
		_tmp46_ = _tmp48_;
	} else {
		_tmp46_ = "";
	}
	_tmp49_ = _tmp27_;
	_tmp50_ = _tmp30_;
	_tmp51_ = _tmp38_;
	_tmp52_ = _tmp41_;
	_tmp53_ = _tmp46_;
	_tmp54_ = g_strdup_printf ("%s%s%s%s%s", _tmp49_, _tmp50_, _tmp51_, _tmp52_, _tmp53_);
	result = _tmp54_;
	_g_free0 (h);
	_g_free0 (_tmp0_);
	return result;
}


static gchar** test_data_create_data (guint count, int* result_length1) {
	gchar** result = NULL;
	guint _tmp0_;
	gchar** _tmp1_ = NULL;
	gchar** numbers;
	gint numbers_length1;
	gint _numbers_size_;
	gchar** _tmp40_;
	gint _tmp40__length1;
	gchar** _tmp41_;
	gint _tmp41__length1;
	_tmp0_ = count;
	_tmp1_ = g_new0 (gchar*, _tmp0_ + 1);
	numbers = _tmp1_;
	numbers_length1 = _tmp0_;
	_numbers_size_ = numbers_length1;
	{
		guint idx;
		idx = (guint) 0;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_;
				guint _tmp5_;
				guint _tmp6_;
				guint _tmp7_;
				guint n;
				gchar* num;
				guint th;
				const gchar* _tmp34_;
				gchar** _tmp36_;
				gint _tmp36__length1;
				guint _tmp37_;
				gchar* _tmp38_;
				gchar* _tmp39_;
				_tmp3_ = _tmp2_;
				if (!_tmp3_) {
					guint _tmp4_;
					_tmp4_ = idx;
					idx = _tmp4_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp5_ = idx;
				_tmp6_ = count;
				if (!(_tmp5_ < _tmp6_)) {
					break;
				}
				_tmp7_ = idx;
				n = _tmp7_ + 1;
				num = NULL;
				th = (guint) 0;
				while (TRUE) {
					guint _tmp8_;
					guint _tmp9_;
					guint _tmp32_;
					guint _tmp33_;
					_tmp8_ = n;
					if (!(_tmp8_ != ((guint) 0))) {
						break;
					}
					_tmp9_ = n;
					if ((_tmp9_ % 1000) != ((guint) 0)) {
						gchar** _tmp10_;
						gint _tmp10__length1;
						guint _tmp11_;
						const gchar* _tmp12_;
						gchar* _tmp13_;
						gchar* t;
						guint _tmp14_;
						gchar* _tmp15_ = NULL;
						gchar* c;
						const gchar* _tmp16_ = NULL;
						const gchar* _tmp17_;
						const gchar* _tmp18_ = NULL;
						const gchar* _tmp19_;
						const gchar* _tmp21_ = NULL;
						const gchar* _tmp22_;
						const gchar* _tmp23_ = NULL;
						const gchar* _tmp24_;
						const gchar* _tmp26_;
						const gchar* _tmp27_;
						const gchar* _tmp28_;
						const gchar* _tmp29_;
						const gchar* _tmp30_;
						gchar* _tmp31_ = NULL;
						_tmp10_ = test_data_thousands;
						_tmp10__length1 = test_data_thousands_length1;
						_tmp11_ = th;
						_tmp12_ = _tmp10_[_tmp11_];
						_tmp13_ = g_strdup (_tmp12_);
						t = _tmp13_;
						_tmp14_ = n;
						_tmp15_ = test_data_print3digit (_tmp14_ % 1000);
						c = _tmp15_;
						_tmp17_ = t;
						if (_tmp17_ != NULL) {
							_tmp16_ = " ";
						} else {
							_tmp16_ = "";
						}
						_tmp19_ = t;
						if (_tmp19_ != NULL) {
							const gchar* _tmp20_;
							_tmp20_ = t;
							_tmp18_ = _tmp20_;
						} else {
							_tmp18_ = "";
						}
						_tmp22_ = num;
						if (_tmp22_ != NULL) {
							_tmp21_ = " ";
						} else {
							_tmp21_ = "";
						}
						_tmp24_ = num;
						if (_tmp24_ != NULL) {
							const gchar* _tmp25_;
							_tmp25_ = num;
							_tmp23_ = _tmp25_;
						} else {
							_tmp23_ = "";
						}
						_tmp26_ = c;
						_tmp27_ = _tmp16_;
						_tmp28_ = _tmp18_;
						_tmp29_ = _tmp21_;
						_tmp30_ = _tmp23_;
						_tmp31_ = g_strdup_printf ("%s%s%s%s%s", _tmp26_, _tmp27_, _tmp28_, _tmp29_, _tmp30_);
						_g_free0 (num);
						num = _tmp31_;
						_g_free0 (c);
						_g_free0 (t);
					}
					_tmp32_ = n;
					n = _tmp32_ / 1000;
					_tmp33_ = th;
					th = _tmp33_ + 1;
				}
				_tmp34_ = num;
				if (_tmp34_ == NULL) {
					gchar* _tmp35_;
					_tmp35_ = g_strdup ("zero");
					_g_free0 (num);
					num = _tmp35_;
				}
				_tmp36_ = numbers;
				_tmp36__length1 = numbers_length1;
				_tmp37_ = idx;
				_tmp38_ = num;
				num = NULL;
				_g_free0 (_tmp36_[_tmp37_]);
				_tmp36_[_tmp37_] = _tmp38_;
				_tmp39_ = _tmp36_[_tmp37_];
				_g_free0 (num);
			}
		}
	}
	_tmp40_ = numbers;
	_tmp40__length1 = numbers_length1;
	numbers = NULL;
	_tmp41_ = _tmp40_;
	_tmp41__length1 = _tmp40__length1;
	if (result_length1) {
		*result_length1 = _tmp41__length1;
	}
	result = _tmp41_;
	numbers = (_vala_array_free (numbers, numbers_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static gint __lambda2_ (const gchar* a, const gchar* b) {
	gint result = 0;
	GCompareFunc _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_val_if_fail (a != NULL, 0);
	g_return_val_if_fail (b != NULL, 0);
	_tmp0_ = g_strcmp0;
	_tmp1_ = a;
	_tmp2_ = b;
	_tmp3_ = _tmp0_ (*((const gchar**) _tmp1_), *((const gchar**) _tmp2_));
	result = _tmp3_;
	return result;
}


static gint ___lambda2__gcompare_data_func (gconstpointer a, gconstpointer b, gpointer self) {
	gint result;
	result = __lambda2_ (a, b);
	return result;
}


static gchar** test_data_sort_array (gchar** array, int array_length1, int* result_length1) {
	gchar** result = NULL;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** _tmp2_;
	gint _tmp2__length1;
	_tmp0_ = array;
	_tmp0__length1 = array_length1;
	g_qsort_with_data (_tmp0_, _tmp0__length1, (gsize) sizeof (gchar*), (GCompareDataFunc) ___lambda2__gcompare_data_func, NULL);
	_tmp1_ = array;
	_tmp1__length1 = array_length1;
	array = NULL;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	array = (_vala_array_free (array, array_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


TestData* test_data_construct (GType object_type) {
	TestData* self = NULL;
	self = (TestData*) g_type_create_instance (object_type);
	return self;
}


TestData* test_data_new (void) {
	return test_data_construct (TYPE_TEST_DATA);
}


static void value_test_data_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_test_data_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		test_data_unref (value->data[0].v_pointer);
	}
}


static void value_test_data_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = test_data_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_test_data_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_test_data_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TestData* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = test_data_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_test_data_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TestData** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = test_data_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_test_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecTestData* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_TEST_DATA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_test_data (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TEST_DATA), NULL);
	return value->data[0].v_pointer;
}


void value_set_test_data (GValue* value, gpointer v_object) {
	TestData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TEST_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TEST_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		test_data_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		test_data_unref (old);
	}
}


void value_take_test_data (GValue* value, gpointer v_object) {
	TestData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TEST_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TEST_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		test_data_unref (old);
	}
}


static void test_data_class_init (TestDataClass * klass) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar** _tmp19_ = NULL;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar** _tmp28_ = NULL;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar** _tmp34_ = NULL;
	guint _tmp35_ = 0U;
	guint _tmp36_;
	gint _tmp37_ = 0;
	gchar** _tmp38_ = NULL;
	gchar** _tmp39_;
	gint _tmp39__length1;
	gchar** _tmp40_;
	gint _tmp40__length1;
	gint _tmp41_ = 0;
	gchar** _tmp42_ = NULL;
	guint _tmp43_;
	gint _tmp44_ = 0;
	guint* _tmp45_ = NULL;
	test_data_parent_class = g_type_class_peek_parent (klass);
	TEST_DATA_CLASS (klass)->finalize = test_data_finalize;
	_tmp0_ = g_strdup ("one");
	_tmp1_ = g_strdup ("two");
	_tmp2_ = g_strdup ("three");
	_tmp3_ = g_strdup ("four");
	_tmp4_ = g_strdup ("five");
	_tmp5_ = g_strdup ("six");
	_tmp6_ = g_strdup ("seven");
	_tmp7_ = g_strdup ("eight");
	_tmp8_ = g_strdup ("nine");
	_tmp9_ = g_strdup ("ten");
	_tmp10_ = g_strdup ("eleven");
	_tmp11_ = g_strdup ("twelve");
	_tmp12_ = g_strdup ("thirteen");
	_tmp13_ = g_strdup ("fourteen");
	_tmp14_ = g_strdup ("fifteen");
	_tmp15_ = g_strdup ("sixteen");
	_tmp16_ = g_strdup ("seventeen");
	_tmp17_ = g_strdup ("eighteen");
	_tmp18_ = g_strdup ("nineteen");
	_tmp19_ = g_new0 (gchar*, 20 + 1);
	_tmp19_[0] = NULL;
	_tmp19_[1] = _tmp0_;
	_tmp19_[2] = _tmp1_;
	_tmp19_[3] = _tmp2_;
	_tmp19_[4] = _tmp3_;
	_tmp19_[5] = _tmp4_;
	_tmp19_[6] = _tmp5_;
	_tmp19_[7] = _tmp6_;
	_tmp19_[8] = _tmp7_;
	_tmp19_[9] = _tmp8_;
	_tmp19_[10] = _tmp9_;
	_tmp19_[11] = _tmp10_;
	_tmp19_[12] = _tmp11_;
	_tmp19_[13] = _tmp12_;
	_tmp19_[14] = _tmp13_;
	_tmp19_[15] = _tmp14_;
	_tmp19_[16] = _tmp15_;
	_tmp19_[17] = _tmp16_;
	_tmp19_[18] = _tmp17_;
	_tmp19_[19] = _tmp18_;
	test_data_ones = _tmp19_;
	test_data_ones_length1 = 20;
	_tmp20_ = g_strdup ("twenty");
	_tmp21_ = g_strdup ("thirty");
	_tmp22_ = g_strdup ("forty");
	_tmp23_ = g_strdup ("fifty");
	_tmp24_ = g_strdup ("sixty");
	_tmp25_ = g_strdup ("seventy");
	_tmp26_ = g_strdup ("eighty");
	_tmp27_ = g_strdup ("ninety");
	_tmp28_ = g_new0 (gchar*, 10 + 1);
	_tmp28_[0] = NULL;
	_tmp28_[1] = NULL;
	_tmp28_[2] = _tmp20_;
	_tmp28_[3] = _tmp21_;
	_tmp28_[4] = _tmp22_;
	_tmp28_[5] = _tmp23_;
	_tmp28_[6] = _tmp24_;
	_tmp28_[7] = _tmp25_;
	_tmp28_[8] = _tmp26_;
	_tmp28_[9] = _tmp27_;
	test_data_tens = _tmp28_;
	test_data_tens_length1 = 10;
	_tmp29_ = g_strdup ("hundred");
	test_data_hundred = _tmp29_;
	_tmp30_ = g_strdup ("thousand");
	_tmp31_ = g_strdup ("million");
	_tmp32_ = g_strdup ("billion");
	_tmp33_ = g_strdup ("trillion");
	_tmp34_ = g_new0 (gchar*, 5 + 1);
	_tmp34_[0] = NULL;
	_tmp34_[1] = _tmp30_;
	_tmp34_[2] = _tmp31_;
	_tmp34_[3] = _tmp32_;
	_tmp34_[4] = _tmp33_;
	test_data_thousands = _tmp34_;
	test_data_thousands_length1 = 5;
	_tmp35_ = test_data_data_size ();
	test_data_DATA_SIZE = _tmp35_;
	_tmp36_ = test_data_DATA_SIZE;
	_tmp38_ = test_data_create_data (_tmp36_, &_tmp37_);
	test_data_data = _tmp38_;
	_tmp39_ = test_data_data;
	_tmp39__length1 = test_data_data_length1;
	_tmp40_ = (_tmp39_ != NULL) ? _vala_array_dup1 (_tmp39_, _tmp39__length1) : ((gpointer) _tmp39_);
	_tmp40__length1 = _tmp39__length1;
	_tmp42_ = test_data_sort_array (_tmp40_, _tmp40__length1, &_tmp41_);
	test_data_sorted_data = _tmp42_;
	_tmp43_ = test_data_DATA_SIZE;
	_tmp45_ = test_data_draw_numbers (_tmp43_, TEST_DATA_RND_IDX_SIZE, &_tmp44_);
	test_data_random_idx = _tmp45_;
}


static void test_data_instance_init (TestData * self) {
	self->ref_count = 1;
}


static void test_data_finalize (TestData* obj) {
	TestData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEST_DATA, TestData);
}


GType test_data_get_type (void) {
	static volatile gsize test_data_type_id__volatile = 0;
	if (g_once_init_enter (&test_data_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_test_data_init, value_test_data_free_value, value_test_data_copy_value, value_test_data_peek_pointer, "p", value_test_data_collect_value, "p", value_test_data_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TestDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) test_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TestData), 0, (GInstanceInitFunc) test_data_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType test_data_type_id;
		test_data_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TestData", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&test_data_type_id__volatile, test_data_type_id);
	}
	return test_data_type_id__volatile;
}


gpointer test_data_ref (gpointer instance) {
	TestData* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void test_data_unref (gpointer instance) {
	TestData* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TEST_DATA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



